name: generate ascii worklfow

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: List Repo files.
          run:  ls -ltra

        - name: Executing shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
        
        - name:
          run: |
            ls -ltra
            pwd

        - name: upload Dragon txt file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon txt file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Test File Exists
          run:  grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon txt file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Read File
          run: cat dragon.txt