name: generate ascii worklfow

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: List Repo files.
          run:  ls -ltra

        - name: Executing shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh

    test_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 seconds
          uses: sleep 10

        - name: Test File Exists
          run:  grep -i "dragon" dragon.txt

    test_job_3:
        runs-on: ubuntu-latest
        steps:
        - name: Read File
          run: cat dragon.txt