name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false     # by default, this is true
      max-parallel: 2      # used to control the number of jobs that run in parallel
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: alpine   # Don't run alpine on Windows
        include:
          - images: amd64/alpine
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info     # docker is preinstalled in github ubuntu by default

      - name: Run Images on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}

  # deploy-on-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Echo Docker Details
  #       run: docker info

  #     - name: Run Images
  #       run: docker run hello-world